### ISSUE TITLE
Increment config

### ISSUE THREAD

**Issue by HHogg** [BrandwatchLtd/remimi#11]
Increment config also accepts `object` so the conditional check needs tweaking. 

https://github.com/BrandwatchLtd/remimi/blob/master/src/mixpanelMiddleware.js#L49

**Comment by kamilio** [comment]
Mixpanel docs https://mixpanel.com/help/reference/javascript-full-api-reference#mixpanel.people.increment

**Comment by HHogg** [comment]
Should be resolved in #16

**Comment by HHogg** [comment]
Now available under [v2.0.1](https://github.com/BrandwatchLtd/remimi/releases/tag/v2.0.1)
